### ISSUE TITLE
Possibility to add summaries at the top of the summary page

### ISSUE THREAD

**Issue by claasd** [jenkinsci/badge-plugin#15]
Hi,

when using createSummary(), the summary is always created at the bottom of the overview page.
There are always messages from before the pipeline run (e.g. SCM messages) above.

Is it somehow possible to add a summary above those messages?

Thanks.

**Comment by bakito** [comment]
@claasd

Hi
I don't think that is possible. The summaty is added as action to the Job by using the method addAction from https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Actionable.java

It seems the actions/summaries are displayed in the order they are added to the job. Since SCM is generally the first thing that is done in the job. These messages come first.

**Comment by claasd** [comment]
Hi,

maybe one could use getActions() and add it as the first one, I will do some experiments.
Thanks for the answer.

Best,
Claas
